[package]
name = "reddit-consume"
version = "0.1.0"
authors = ["wucke13 <wucke13@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
mpvipc = "1"
roux = "1"
tokio = { version = "1", features = ["full"] }
