[package]
name = "reddit-consume"
version = "0.1.0"
authors = ["wucke13 <wucke13@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
ureq = { version = "0.11", features = [ "json", "tls" ] }

#serde_json = "1.0"
