name: Nix
permissions:
  contents: write
on:
  pull_request: null
  push:
    branches:
      - main
jobs:
  x86_64-linux---packages---default:
    name: x86_64-linux---packages---default
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix build .#packages.x86_64-linux.default --print-build-logs
  x86_64-linux---devShells---default:
    name: x86_64-linux---devShells---default
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix build .#devShells.x86_64-linux.default --print-build-logs
  x86_64-linux---check:
    name: Check on x86_64-linux
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check
        run: nix flake check . --print-build-logs
  i686-linux---packages---default:
    name: i686-linux---packages---default
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix build .#packages.i686-linux.default --print-build-logs
  i686-linux---devShells---default:
    name: i686-linux---devShells---default
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix build .#devShells.i686-linux.default --print-build-logs
  i686-linux---check:
    name: Check on i686-linux
    runs-on:
      - ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check
        run: nix flake check . --print-build-logs
